name: Build PDF
on: [push]
jobs:
  build_latex:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TeXLive and compile document
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
            apk add file sudo coreutils
            chmod +x scripts/install_fonts.sh
            scripts/install_fonts.sh
            cat mtpro2-texlive.sh.log
            latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode clrs4e-solutions.tex

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: clrs4e-solutions.pdf
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
